### ISSUE TITLE
Live.php - Real time traffic monitor does not display traffic

### ISSUE THREAD

**Issue by gm1ymi** [sq8vps/aprx-simplewebstat#34]
When clicking on Real time traffic monitor it opens another window but no traffic is displayed.

Live.php - Line 82
<script src="http://creativecouple.github.com/jquery-timing/jquery-timing.min.js"></script>
Change to:
<script src="http://creativecouple.github.io/jquery-timing/jquery-timing.min.js"></script>

You get a 404 trying to connect to *.github.com as of 15/4/2021.

**Comment by sq8vps** [comment]
It's already changed. Please check if it's working now.

**Comment by gm1ymi** [comment]
Yes, should have checked the repo... Thanks!
